{% set name = "sncosmo" %}
{% set version = "1.8.0" %}
{% set sha256 = "93590c47ac5d5a4849b622d2fba8a867d31b8697363c19abe85d040b9e970ba0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    # If cython sources were included, we could just rerender them here to make
    # the package work with 3.7.
    # - cythonize sncosmo/*.pyx  # [py>36]
    - pip install . --no-deps --ignore-installed --no-cache-dir

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - astropy
    - extinction

test:
  imports:
    - sncosmo

about:
  home: https://github.com/sncosmo/sncosmo
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: 'Python library for supernova cosmology'
  description: |
    SNCosmo synthesizes supernova spectra and photometry from SN models,
    and has functions for fitting and sampling SN model parameters given
    photometric light curve data. It includes supernova models such as SALT2,
    MLCS2k2, Hsiao, Nugent, PSNID, SNANA and Whalen models, as well as a
    variety of built-in bandpasses and magnitude systems, and provides
    convenience functions for reading and writing commonly used data formats.
    The library is extensible, allowing user-defined models, bandpasses,
    and magnitude systems.
  doc_url: http://sncosmo.readthedocs.io/
  dev_url: https://github.com/sncosmo/sncosmo

extra:
  recipe-maintainers:
    - kbarbary
    - mwcraig
