{% set name = "sncosmo" %}
{% set version = "2.5.0" %}
{% set sha256 = "5b2fa9f42e10b1347405585bd54552aef83a6dcccccade7fb8e6ef65732cf351" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py27]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - astropy
    - extinction

test:
  imports:
    - sncosmo

about:
  home: https://github.com/sncosmo/sncosmo
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python library for supernova cosmology
  description: |
    SNCosmo synthesizes supernova spectra and photometry from SN models,
    and has functions for fitting and sampling SN model parameters given
    photometric light curve data. It includes supernova models such as SALT2,
    MLCS2k2, Hsiao, Nugent, PSNID, SNANA and Whalen models, as well as a
    variety of built-in bandpasses and magnitude systems, and provides
    convenience functions for reading and writing commonly used data formats.
    The library is extensible, allowing user-defined models, bandpasses,
    and magnitude systems.
  doc_url: http://sncosmo.readthedocs.io/
  dev_url: https://github.com/sncosmo/sncosmo

extra:
  recipe-maintainers:
    - kbarbary
    - mwcraig
    - kboone
    - benjaminrose
    - jpierel14
    - rbiswas4
